
#Oliver Linger 120444372
from processes import Processes
from mlfq import MLFQ
# Instead of manually inserting processes, 
# they are generated by a loop. Some have a probability of being an IO bound process. 
# Processes are generated in the process class
# They are first part of an list of processes to be added to the ready Queues. 
# After all processes are executed the idle process takes over.
# 6 processes are generated in the process class, but far more can be generated if wished, thisisdoneby increasing the range in the for loop.
class Test:
    if __name__ == '__main__':
        def test():
            P = Processes()
            Q = MLFQ(P._listOfProcesses)
            Q.addingToQueues()
            Q.blockedProcesses()
            Q.executingProcesses()
        test()